import enum
from sys import implementation
from typing import Iterable

TOPIC_BAFIN: str = "bafin_event"
TOPIC_BAFIN_PERSON: str = "bafin_person"
TOPIC_BAFIN_CORPORATE: str = "bafin_corporate"
class Letter(str, enum.Enum):
    A = "a"
    B = "b"
    C = "c"
    D = "d"
    E = "e"
    F = "f"
    G = "g"
    H = "h"
    I = "i"
    J = "j"
    K = "k"
    L = "l"
    M = "m"
    N = "n"
    O = "o"
    P = "p"
    Q = "q"
    R = "r"
    S = "s"
    T = "t"
    U = "u"
    V = "v"
    W = "w"
    X = "x"
    Y = "y"
    Z = "z"